# Assumes that conda, pip, build-essentials and cuda are installed
---
name: FiniteVolumeGPU_HPC
channels:
- conda-forge

dependencies:
- python=3.13.5
- pip
- numpy
- mpi4py
- six
- pytools
- netcdf4
- scipy
- tqdm
- pip:
  - hip-python==6.4.1.552.39
  - -i https://test.pypi.org/simple/


# Install conda environment (one-time operation):
# $ conda env create -f conda_environment.yml
# Activate environment
# $ conda activate FiniteVolumeGPU_HPC

# OPTIONAL: If you want to compile pycuda yourself, uncomment pycuda under 
# "dependencies" above and do the following (one-time operation):
#  - pycuda: $ pip3 install --no-deps -U pycuda
# on Windows: make sure your visual studio c++ compiler is available in PATH
# PATH should have something like C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\
